// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcspFF5CYjmwbpkGqoEGTI0uAhtk4PE7c',
    appId: '1:75695770591:web:9d6a418510a8cfae66526a',
    messagingSenderId: '75695770591',
    projectId: 'walmartsparkathon',
    authDomain: 'walmartsparkathon.firebaseapp.com',
    storageBucket: 'walmartsparkathon.appspot.com',
    measurementId: 'G-SM8NSRWYBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETRBOhHWbk3QezigTayy68YgCN7BmSwk',
    appId: '1:75695770591:android:bce7d6b8d73b2aee66526a',
    messagingSenderId: '75695770591',
    projectId: 'walmartsparkathon',
    storageBucket: 'walmartsparkathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA9Nx9LfQNkJgziWcqpeq4zMF_dwW8qT8',
    appId: '1:75695770591:ios:6a9e00fca9ce789d66526a',
    messagingSenderId: '75695770591',
    projectId: 'walmartsparkathon',
    storageBucket: 'walmartsparkathon.appspot.com',
    iosBundleId: 'com.example.emergingTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA9Nx9LfQNkJgziWcqpeq4zMF_dwW8qT8',
    appId: '1:75695770591:ios:6a9e00fca9ce789d66526a',
    messagingSenderId: '75695770591',
    projectId: 'walmartsparkathon',
    storageBucket: 'walmartsparkathon.appspot.com',
    iosBundleId: 'com.example.emergingTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcspFF5CYjmwbpkGqoEGTI0uAhtk4PE7c',
    appId: '1:75695770591:web:69fb7b4f5fe8d95466526a',
    messagingSenderId: '75695770591',
    projectId: 'walmartsparkathon',
    authDomain: 'walmartsparkathon.firebaseapp.com',
    storageBucket: 'walmartsparkathon.appspot.com',
    measurementId: 'G-Y5N17QPB19',
  );
}
